const {
  NEXT_PUBLIC_REACT_APP_API_URL,
  NEXT_PUBLIC_REACT_APP_IMAGEKIT_URL,
  NEXT_PUBLIC_REACT_APP_IMAGEKIT_PUBLIC_KEY,
  NEXT_PUBLIC_REACT_APP_IMAGEKIT_AUTH_URL,
  NEXT_PUBLIC_REACT_APP_IMAGEKIT_DELETE_URL,
  NEXT_PUBLIC_REACT_APP_URL,
  // cookies
  NEXT_PUBLIC_REACT_APP_LANGUAGE,
  // map box
  NEXT_PUBLIC_REACT_APP_MAPBOX_API,
} = process.env;

const config = {
  url: NEXT_PUBLIC_REACT_APP_URL,
  imagekitUrl: NEXT_PUBLIC_REACT_APP_IMAGEKIT_URL,
  imagekitPublicKey: NEXT_PUBLIC_REACT_APP_IMAGEKIT_PUBLIC_KEY,
  imagekitAuthUrl: NEXT_PUBLIC_REACT_APP_IMAGEKIT_AUTH_URL,
  imagekitDeleteUrl: NEXT_PUBLIC_REACT_APP_IMAGEKIT_DELETE_URL,
  // cookie
  language: NEXT_PUBLIC_REACT_APP_LANGUAGE,
  apiUrl: NEXT_PUBLIC_REACT_APP_API_URL,
  // map box api
  mapBoxAPI: NEXT_PUBLIC_REACT_APP_MAPBOX_API,
};

export default config;
